version: '3'
services:
        portainer:
                image: portainer/portainer:latest
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - portainer_data:/data
                restart: always
                ports:
                        - "9000:9000"

        jupyter:
                image: 2281995/bdp2_assignment:latest
                volumes:
                        - /home/ubuntu/assignment/bdp2_assignment/work:/home/jovyan/work
                environment:
                        - GEN_CERT=yes
                ports:
                        - "8888:8888"


volumes:
        portainer_data: {}
                
